steps:
  - name: 'docker/compose:1.15.0'
    args: ['-p', 'app', '-f', 'docker-compose-local.yml', 'up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['ps']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['exec', 'app_web_1', './manage.py', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'raporty_local_python:latest', 'gcr.io/$PROJECT_ID/raporty-app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'raporty_local_python:latest', 'gcr.io/$PROJECT_ID/raporty-app:$SHORT_SHA']

images: [
  'gcr.io/$PROJECT_ID/raporty-app:latest',
  'gcr.io/$PROJECT_ID/raporty-app:$SHORT_SHA',
]
